modLoader="javafml"
loaderVersion="[36,)"
license="niceFilms Official license"

[[mods]]
modId="djfilmsmi"
version="1.0.1"
displayName="More Items By DJ_Films"
credits="MORE ITEMS YES"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="DJ_Films, niceEli, and Nicc"
description='''
A Small Mod That Adds A Few Items
'''

[[dependencies.djfilmsmi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




